trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: DEV_ENVIRONMENT
  value: dev

stages:
- stage: TerraformValidate
  jobs:
    - job: TerraformValidateJob
      continueOnError: false
      